version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8080:8080"
    # volumes:
    #   - ./app:/app/app
    #   - ./app/data.csv:/app/app/data.csv
    #   - ./app/selected.csv:/app/app/selected.csv
    #   - ./app/logs:/app/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: fastapi-mqtt-network