version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: fastapi-mqtt-network